### ISSUE TITLE
Need conditional modifier support

### ISSUE THREAD

**Issue by Aaron-Pool** [tenphi/angular-bem#12]
Could we get something to where, if we have value disabled in the provider config, then the thing after the colon could be a condition to evaluate as to whether to add a modifier or not?

example `<div elem="button" mod="disabled: $ctrl.isDisabled">`

So `button--disabled` would only be applied if `$ctrl.isDisabled` was true.

EDIT: Ok, looking at the code, this looks like it might already be the case, but I can't tell from the docs.

**Comment by tenphi** [comment]
Yes, this is how it works. Just try. :)

**Comment by tenphi** [comment]
Docs were updated to bring more clarify.

**Comment by Aaron-Pool** [comment]
Thanks for the follow up and the quick reply!
