### ISSUE TITLE
support for mixes

### ISSUE THREAD

**Issue by Aaron-Pool** [tenphi/angular-bem#14]
I'm starting to run into some structural issues that can only be handled with BEM mixes, however, there's no current support for them in Angular Bem.

For reference: https://en.bem.info/forum/4/

Basically, it's having two blocks on the same DOM node. I understand that this is inherently difficult, based on the way you have the thing set up, which is why I would suggest adding a new directive, instead of modifying the existing base.

Something like this 

```
<input block="my-specific-form" mod="active" mix-block="my-generic-form: {mod1: true; mod2: false; mod3: true}">
   <span elem="text"></span>
</input>
```

And the outputted html would be

```
<input class="my-specific-form--active my-generic-form--mod1 my-generic-form--mod3">
  <span class="my-specific-form__text"></span>
</input>
```

The use cases for mixes listed on the BEM faq are as follows:

A single DOM node can represent:
- several blocks `<div class="menu head-menu"></div>`
- a block and an element of the same block `<div class="menu menu__layout"></div>`
- a block and an element of another block `<div class="link menu__link"></div>`
- elements of different blocks `<div class="menu__item head-menu__item"></div>`
- a block with a modifier and another block `<div class="menu menu_layout_horiz head-menu">`
- several different blocks with modifiers `<div class="menu menu_layout_horiz head-toolbar head-toolbar_theme_black"><div>`

My suggestion doesn't account for mixing elements, but that seems substantially less useful than mixing blocks. That would require some deeper thought, I suppose.

**Comment by Aaron-Pool** [comment]
I might be able to do a PR, if you're looking for one.

**Comment by tenphi** [comment]
There is no need for such mixes. I discussed these things with BEM core team and they didn't convince me that BEM should cover these cases.

As for me I use global mix-classes to extend element styles if I need and don't mix BEM-instances at all.

I prefer component approach. And components can only contain each other.

I've used angular-bem for two years and I didn't face a single case where I need to use mixes you talking about. There was always a better and cleaner approach.

**Comment by tenphi** [comment]
If we would add such mixes to the library we would have absolutely new library with much more complicated syntax and noticeable performance problems.

**Comment by Aaron-Pool** [comment]
Ok, so I want to create a site-wide generic base-style block I can mixin to input field elements to create a unifying look to forms and not have to duplicate styles all over. How would you do this under the BEM convention without mixins?

**Comment by tenphi** [comment]
Just stop thinking in terms of blocks only.
Use simple mixin css class. To simplify things I suggest you use prefix for such classes.

**Comment by Aaron-Pool** [comment]
Alright, I'll consider that, thanks! I guess I was just hoping to be as consistent as possible for the sake of setting a clear standard for other members of the team to conform to. I'm afraid if I start throwing mixin classes on things, things may get out of hand quickly. But I understand your hesitation to complicate a clean solution for the sake of potential edge cases.

**Comment by tenphi** [comment]
I forgot to mention that mixin classes are good for layout fixes but using them inside block templates is a bad idea.

BUT you can use mixins (and vars) in style preprocessor. It is still not a perfect solution but it works very well for mid-size projects.
