### ISSUE TITLE
Need a way to rescope to elements to a block without actually applying the block css class.

### ISSUE THREAD

**Issue by Aaron-Pool** [tenphi/angular-bem#15]
For directives using transclusion, the block hierarchy can often be broken by the directive transcluding content, even when we still want the transcluded content to be a part of our current components scope. 

Example:

```
<outer-component block="outer-component">
      <custom-expander block="custom-expander">
            <div elem="expanding-content">
                    I want to use the expanding functionality of my parent directive,
                    but I don't really belong to it's block. I belong to outer-component!
            </div>
      </custom-expander>
</outer-component>
```

Now, of course, you could rescope it like this:

```
<outer-component block="outer-component">
      <custom-expander block="custom-expander">
            <div block="outer-component" elem="expanding-content">
                    I want to use the expanding functionality of my parent directive,
                    but I don't really belong to it's block. I belong to outer-component!
            </div>
      </custom-expander>
</outer-component>
```

But now any style I applied to `outer-component` are applied to `expanding-content` as well.

Currently I use this work-around:

```
<outer-component block="outer-component">
      <div elem="wrapper">
          <custom-expander block="custom-expander">
                <div block="outer-component" elem="expanding-content">
                    I want to use the expanding functionality of my parent directive,
                    but I don't really belong to it's block. I belong to outer-component!
                </div>
          </custom-expander>
      </div>
</outer-component>
```

And leave the block element unstyled so that I can rescope to a particular block without
messing up the flow of the page, however, I think this would be much cleaner and relatively simple
to implement:

```
<outer-component block="outer-component">
      <custom-expander block="custom-expander">
            <div block-scope="outer-component" elem="expanding-content">
                    I want to use the expanding functionality of my parent directive, 
                    but I don't really belong to it's block. I belong to outer-component!
            </div>
      </custom-expander>
</outer-component>
```

If this sounds reasonable, but you're really not interested in implementing it, I'd consider submitting a pull-request. Just let me know.

**Comment by tenphi** [comment]
You try to make component that has its element inside other component. It's serious conceptional mistake. Of course, you can do whatever you want in your app, but these features won't be part of angular-bem, because it will turn angular-bem into completely different library without backward-compatibility and will make it much slower in performance and harder to understand. Also you will have to change syntax.

Anyway I don't see any problem in your code. You can use decorator-directive if you want. Just make sure it has non-isolated scope. I don't have time right now to test it.

To use single block notation for single component is the best approach for me. I don't use angular-bem notations outside of the components templates.

So this part of template doesn't make sense for me: `<outer-component block="outer-component">`
Such `block` notation should be inside of the `outer-component`'s template.

**Comment by Aaron-Pool** [comment]
Yes, I suppose "component" terminology was a poor use of words. The internal component is more of a decorator, as you said. Either way, my decorator is reusable, so I treat is as a BEM block, but since it's a wrapper for content intended to be within another component, it seems like the content within the wrapper should still be scoped to the outer component. For example, if I'm making `groceryList` component which has `groceryLineItems`. If `groceryLineItems` and `groceryList` are only ever used together, they classify as a single BEM block, correct? So I want `groceryLineItem` to be an element of `groceryList`, instead of a seperate block. BUT suppose I want to use an expander block around every `groceryLineItem` component. I have no way of keeping that scoped to the same BEM block. I don't see how this is a conceptual mistake. In fact, I'm not exactly sure how it could be a performance issue either.

As for the part at the end where you say my block notation should be inside the outer-components template, this creates a strange issue with flex box and styling relationships where there is a "ghost" DOM layer between the flex parent and flex child. For example:

Parent Component:

```
<div block="parent-component">
    <div elem="gallery">
          // large boolean will add a modifier
          <photo url="url1" large="$first" ng-repeat="photos in $ctrl.photoList"></photo>
    </div>
</div>
```

Parent Style:

```
.parent-component {
     display: flex;
     flex-flow: column;
     align-item: center;
}
```

Child Component:

```
<div block="photo" mod="large: $ctrl.large">
     // template html
</div>
```

Child Style:

```
.photo {
       /* main styles here*/

     &--large {
          flex: none;
          height: 500px;
     }
}
```

This won't work, because the additional dom elements added as a wrapper around component content (replace is now deprecated) breaks the dom chain and, therefor, breaks the flex layout.

So the output html is something like this:

```
<div block="parent-component">
    <div elem="gallery">
          <photo url="url1" ng-repeat="photos in photoList">
                 <div class="block block--large">
                    // photo html
                 </div>
          </photo>
    </div>
</div>
```

That's why I add block elements directly to the main component markup. 

I'm still confused why you think being able to rescope to a particular block is a "serious conceptual mistake" or "angular-bem into completely different library without backward-compatibility and will make it much slower in performance and harder to understand". All I'm advocating is having one additional directive which would only affect block scope, as opposed to applying the block styles. Which seems simple to me, but, of course, I could be mistaken. In the absence of said directive, you have to do one of the below:

1) Break the BEM convention for your decorator component so as to not pollute the block
scope for the child content.
2) Create a new block for all internal content of a decorator component, which can be annoying if the 
content is nominal and should be associated with the parent block anyways.

**Comment by tenphi** [comment]
Some things are just broken. There is no need to fix them. Component approach (HTML5 or Angular with deprecated `replace` flag) will always have issue with direct nesting. (flex styling or other problems)

Don't use block notation in decorators. It's much easier solution than complication of library.

I got your point. Yes, we can define additional directive to support such scenario. But I doesn't have any intention to help developers in writing bad code.

Sometimes we should just avoid problems without solving them.

**Comment by Aaron-Pool** [comment]
Fair enough.
