### ISSUE TITLE
classList.add not supported on svg elements in IE

### ISSUE THREAD

**Issue by davestaab** [tenphi/angular-bem#16]
Apparently classList.add is not supported on svg elements in IE.
**Reference: http://caniuse.com/#feat=classlist**
This has been fixed in edge but there's apparently no work to implement this in IE 11 or below. 

I started making a pull request to drop classList entirely. I see you have function for addClass for browsers that don't support classList and you have a clissListSupport check. What's the reasoning for the two sets of functions. Does classList have better performance? 

I'm open to input on ways to address this issue. I'll submit a pull request. Take a look and let me know what you want to do.

**Comment by tenphi** [comment]
Hi! Can you recreate your pull request to `v1` branch?
