### ISSUE TITLE
Изменение класса из контроллера

### ISSUE THREAD

**Issue by germani** [tenphi/angular-bem#5]
Андрей привет отличный модуль для ускорения верстки где нет возмоности полного стека бем, подскажи есть ли возможность изменения класа из контроллера простым изменением модифиатора елемента?
Я тут сделал не большой пример о чем идет речь.... может я просто ни так что то делаю?
http://plnkr.co/edit/0IL848VCL2lGCBKngtrl?p=info

Заранее спасибо за ответ

**Comment by tenphi** [comment]
Привет! Спасибо.

Ты неправильно используешь ангуляр. В нём другая философия. Контроллер тут хранит в скоупе только состояние и работает только с ним, а с классами (в 99% случаев) работает непосредственно шаблон.

http://plnkr.co/edit/1yQNAPSRWL2mumcqhen2?p=preview

Работа напрямую с $element требуется довольно редко. Почти всегда можно ограничиться манипуляцией над скоуп и правильными байндингами.

**Comment by germani** [comment]
Спасибо, да действительно не верно пытался поменять состояние.
