### ISSUE TITLE
Modifier's value are appended with "-" and not "_"

### ISSUE THREAD

**Issue by fabm22** [tenphi/angular-bem#6]
Hi.

Currently with the version i found here  https://raw.githubusercontent.com/tenphi/angular-bem/master/angular-bem.js 

the modifiers value produce values of modifiers with "-" between modifier and its value. Ex :
`block="block"    ... elem="part"  mod="{variation: 'test' }"`
will produce   `block__part--variation-test`.  
Shouldn't this produce :   `block__part--variation_test`  with a `_` as we see in the docs ?? Is it expected ?

Thanks a lot

**Comment by tenphi** [comment]
Hi!

block__part--variation-test is correct.
there is a mistake in docs. thanks for noticing! I'll fix it soon.

you can customize syntax as described in docs if you want.
